name: Rebuild

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */1 * * *'  # Every hour

jobs:
  update-key:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Save your personal private key
        echo "${{ secrets.MLOPSKEY_PRIVATE }}" > ~/.ssh/mlopskey
        chmod 600 ~/.ssh/mlopskey
        
        # Save your public key
        echo "${{ secrets.MLOPSKEY_PUBLIC }}" > ~/.ssh/mlopskey.pub
        
        # Save the old student-admin key
        echo "${{ secrets.STUDENT_ADMIN_KEY }}" > ~/.ssh/student-admin_key
        chmod 600 ~/.ssh/student-admin_key
        
        # Disable host key checking
        echo "StrictHostKeyChecking no" > ~/.ssh/config
    
    - name: Try connecting with personal key
      id: check_personal
      continue-on-error: true
      run: |
        ssh -i ~/.ssh/mlopskey -p 22012 student-admin@paffenroth-23.dyn.wpi.edu "echo 'Personal key works'"
    
    - name: Update key if personal key failed
      if: steps.check_personal.outcome == 'failure'
      run: |
        echo "Personal key failed, using student-admin key to update..."
        
        # Connect with old key and update authorized_keys
        ssh -i ~/.ssh/student-admin_key -p 22012 student-admin@paffenroth-23.dyn.wpi.edu << 'EOF'
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          
          # Remove old student-admin key and add personal key
          grep -v "rcpaffenroth@paffenroth-23" ~/.ssh/authorized_keys > ~/.ssh/authorized_keys.tmp || true
          mv ~/.ssh/authorized_keys.tmp ~/.ssh/authorized_keys
          cat >> ~/.ssh/authorized_keys
        EOF
        
        # Pipe your public key into the SSH command
        cat ~/.ssh/mlopskey.pub | ssh -i ~/.ssh/student-admin_key -p 22012 student-admin@paffenroth-23.dyn.wpi.edu "cat >> ~/.ssh/authorized_keys"
    
    - name: Verify personal key works
      run: |
        echo "Verifying personal key..."
        ssh -i ~/.ssh/mlopskey -p 22012 student-admin@paffenroth-23.dyn.wpi.edu "echo 'Success: Personal key is working'"
